### ISSUE TITLE
1.0 Create private repository

### ISSUE THREAD

**Issue by rStrzelczyk98** [rStrzelczyk98/chat-app#7]
# Resources: 

- [Design](https://www.figma.com/file/FgUhKJjQdgpG6nzWqKklN5/Agency-Landing-Page-(Community))
- [Bootstrap documentation](https://getbootstrap.com/docs/5.3/getting-started/introduction/)

# Tasks:
- [ ] create a private repository
- [ ] add mentors to the repository
- [ ] create init commit with HTML, CSS, and README
